version: '3.9'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bambu-dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"   # Backend
      - "5173:5173"   # Vite dev server (Vue frontend)
    working_dir: /app
    tty: true